image:
  repository: louislam/uptime-kuma
  tag: "1"

service:
  port: 3001

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

storage:
  size: 2Gi
  storageClass: gp2

config:
  nodeEnv: production
  port: "3001"

secret:
  appPassword: ""
