apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv }}
  PORT: {{ .Values.config.port | quote }}
